.TH "KMeans_MapReduce::KMPoint::KeyHasher" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KMeans_MapReduce::KMPoint::KeyHasher \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::size_t \fBoperator()\fP (const \fBKMPoint\fP &centroid) const "
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "std::size_t KMeans_MapReduce::KMPoint::KeyHasher::operator() (const \fBKMPoint\fP &centroid) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
