.TH "KMeans::ThreadArgNewCentroid" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KMeans::ThreadArgNewCentroid \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t * \fBchunkIndices\fP"
.br
.ti -1c
.RI "std::vector< \fBKMPoint\fP * > * \fBinput\fP"
.br
.ti -1c
.RI "\fBKMPoint\fP \fBcentroid\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBKMPoint\fP KMeans::ThreadArgNewCentroid::centroid"

.SS "size_t* KMeans::ThreadArgNewCentroid::chunkIndices"

.SS "std::vector<\fBKMPoint\fP *>* KMeans::ThreadArgNewCentroid::input"


.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
