.TH "KMeans::ThreadArgClosestCentroid" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KMeans::ThreadArgClosestCentroid \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBKMPoint\fP * > * \fBinput\fP"
.br
.ti -1c
.RI "std::vector< \fBKMPoint\fP > * \fBcentroids\fP"
.br
.ti -1c
.RI "size_t * \fBchunkIndices\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBKMPoint\fP>* KMeans::ThreadArgClosestCentroid::centroids"

.SS "size_t* KMeans::ThreadArgClosestCentroid::chunkIndices"

.SS "std::vector<\fBKMPoint\fP*>* KMeans::ThreadArgClosestCentroid::input"


.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
