.TH "KMeans_MapReduce::KMPoint" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KMeans_MapReduce::KMPoint \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBKeyHasher\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBKMPoint\fP &p) const "
.br
.ti -1c
.RI "void \fBprint\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBhasChanged\fP"
.br
.ti -1c
.RI "\fBCOORD\fP \fBcoord\fP"
.br
.ti -1c
.RI "\fBCOORD\fP \fBcluster\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool KMeans_MapReduce::KMPoint::operator== (const \fBKMPoint\fP &p) const\fC [inline]\fP"

.SS "void KMeans_MapReduce::KMPoint::print ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBCOORD\fP KMeans_MapReduce::KMPoint::cluster"

.SS "\fBCOORD\fP KMeans_MapReduce::KMPoint::coord"

.SS "bool KMeans_MapReduce::KMPoint::hasChanged"


.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
