.TH "/afs/inf.ed.ac.uk/user/s18/s1837296/dev/stencil/Distribute/main.cpp" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/afs/inf.ed.ac.uk/user/s18/s1837296/dev/stencil/Distribute/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'testMap\&.hpp'\fP
.br
\fC#include 'testReduce\&.hpp'\fP
.br
\fC#include 'testMapReduce\&.hpp'\fP
.br
\fC#include 'testScan\&.hpp'\fP
.br
\fC#include 'problemKmeans\&.hpp'\fP
.br
\fC#include 'problemKmeans_MR\&.hpp'\fP
.br
\fC#include 'problemRadixsort\&.hpp'\fP
.br
\fC#include 'problemSummedArea\&.hpp'\fP
.br
\fC#include 'def_file\&.hpp'\fP
.br
\fC#include 'miscFun\&.hpp'\fP
.br
\fC#include 'MapReduce\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
