.TH "MapReduceSkeleton" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapReduceSkeleton \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MapReduce\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMapReduceImplementation\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename HA2 , typename EL2 , typename RE2 > \fBMapReduceSkeleton::MapReduceImplementation\fP
.br
< EL2, RE2, HA2 > \fB__MapReduceWithAccess\fP (EL2 el, RE2 re, HA2 hasher, size_t threads)"
.br
.in -1c
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename HA2 , typename EL2 , typename RE2 > \fBMapReduceSkeleton::MapReduceImplementation\fP<EL2, RE2, HA2> __MapReduceWithAccess (EL2el, RE2re, HA2hasher, size_tthreads)\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
