.TH "MapSkeleton::MapImplementation< EL >" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapSkeleton::MapImplementation< EL > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Map\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename IN , typename OUT , typename\&.\&.\&. ARGs> void \fBoperator()\fP (std::vector< OUT > &output, std::vector< IN > &input, ARGs\&.\&.\&.args)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename EL2 > \fBMapImplementation\fP< EL2 > \fB__MapWithAccess\fP (EL2 el, const size_t &threads)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename EL>class MapSkeleton::MapImplementation< EL >"
\fBMapImplementation\fP 
.SH "Member Function Documentation"
.PP 
.SS "template<typename EL> template<typename IN , typename OUT , typename\&.\&.\&. ARGs> void \fBMapSkeleton::MapImplementation\fP< EL >::operator() (std::vector< OUT > &output, std::vector< IN > &input, ARGs\&.\&.\&.args)\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename EL> template<typename EL2 > \fBMapImplementation\fP<EL2> __MapWithAccess (EL2el, const size_t &threads)\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
