.TH "/afs/inf.ed.ac.uk/user/s18/s1837296/dev/stencil/Distribute/miscFun.cpp" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/afs/inf.ed.ac.uk/user/s18/s1837296/dev/stencil/Distribute/miscFun.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/time\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'miscFun\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBjustAMoment\fP (size_t n)"
.br
.ti -1c
.RI "double \fBsecond\fP ()"
.br
.ti -1c
.RI "void \fBprintResults\fP (size_t threads, size_t RUNS, double *\fBseqTime\fP, double seqAVG, double *\fBskelTime\fP, double skelAVG, double gain)"
.br
.ti -1c
.RI "void \fBprintMessage\fP (std::string s)"
.br
.ti -1c
.RI "int \fBiRand\fP (int iMin, int iMax)"
.br
.ti -1c
.RI "double \fBfRand\fP (double fMin, double fMax)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "double \fBtstart\fP"
.br
.ti -1c
.RI "double \fBtstop\fP"
.br
.ti -1c
.RI "double \fBskelTime\fP [NRUNS]"
.br
.ti -1c
.RI "double \fBseqTime\fP [NRUNS]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double fRand (doublefMin, doublefMax)"

.SS "int iRand (intiMin, intiMax)"

.SS "void justAMoment (size_tn)"

.SS "void printMessage (std::strings)"

.SS "void printResults (size_tthreads, size_tRUNS, double *seqTime, doubleseqAVG, double *skelTime, doubleskelAVG, doublegain)"

.SS "double second ()"

.SH "Variable Documentation"
.PP 
.SS "double seqTime[NRUNS]"

.SS "double skelTime[NRUNS]"

.SS "double tstart"

.SS "double tstop"

.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
