.TH "/afs/inf.ed.ac.uk/user/s18/s1837296/dev/stencil/Distribute/Pipeline.hpp" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/afs/inf.ed.ac.uk/user/s18/s1837296/dev/stencil/Distribute/Pipeline.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <typeinfo>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <thread>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPipeStageBase\fP"
.br
.ti -1c
.RI "class \fBPipeStage< IN, OUT >\fP"
.br
.ti -1c
.RI "class \fBPipeline\fP"
.br
.ti -1c
.RI "class \fBPipelineInit\fP"
.br
.ti -1c
.RI "class \fBStage1\fP"
.br
.ti -1c
.RI "class \fBStage2\fP"
.br
.ti -1c
.RI "class \fBStage3\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBStage1\fP \fBstage1\fP"
.br
.ti -1c
.RI "\fBStage2\fP \fBstage2\fP"
.br
.ti -1c
.RI "\fBStage3\fP \fBstage3\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS " \fBStage1\fP stage1"

.SS " \fBStage2\fP stage2"

.SS " \fBStage3\fP stage3"

.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
