.TH "PipeStageBase" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PipeStageBase \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Pipeline\&.hpp>\fP
.PP
Inherited by \fBPipeStage< IN, OUT >\fP\fC [private]\fP, \fBPipeStage< double, string >\fP\fC [private]\fP, \fBPipeStage< int, double >\fP\fC [private]\fP, and \fBPipeStage< string, double >\fP\fC [private]\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
