.TH "/afs/inf.ed.ac.uk/user/s18/s1837296/dev/stencil/Distribute/problemSummedArea.hpp" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/afs/inf.ed.ac.uk/user/s18/s1837296/dev/stencil/Distribute/problemSummedArea.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBSummedArea\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBSummedArea::SummedAreaMain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
