.TH "ReduceSkeleton::ReduceImplementation< CO >" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReduceSkeleton::ReduceImplementation< CO > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Reduce\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename IN , typename\&.\&.\&. ARGs> void \fBoperator()\fP (IN &output, std::vector< IN > &input, ARGs\&.\&.\&.args)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename CO2 > \fBReduceSkeleton::ReduceImplementation\fP
.br
< CO2 > \fB__ReduceWithAccess\fP (CO2 co, const size_t &threads)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename CO> template<typename IN , typename\&.\&.\&. ARGs> void \fBReduceSkeleton::ReduceImplementation\fP< CO >::operator() (IN &output, std::vector< IN > &input, ARGs\&.\&.\&.args)\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename CO> template<typename CO2 > \fBReduceSkeleton::ReduceImplementation\fP<CO2> __ReduceWithAccess (CO2co, const size_t &threads)\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
