.TH "/afs/inf.ed.ac.uk/user/s18/s1837296/dev/stencil/Distribute/Scan.hpp" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/afs/inf.ed.ac.uk/user/s18/s1837296/dev/stencil/Distribute/Scan.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <typeinfo>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <condition_variable>\fP
.br
\fC#include <stack>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScanSkeleton\fP"
.br
.ti -1c
.RI "class \fBScanSkeleton::ScanImplementation< SU >\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename SU > \fBScanSkeleton::ScanImplementation\fP
.br
< SU > \fB__ScanWithAccess\fP (SU su, const size_t &threads)"
.br
.ti -1c
.RI "template<typename SU > \fBScanSkeleton::ScanImplementation\fP
.br
< SU > \fBScan\fP (SU su, const size_t &threads=0)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename SU > \fBScanSkeleton::ScanImplementation\fP<SU> __ScanWithAccess (SUsu, const size_t &threads)"

.SS "template<typename SU > \fBScanSkeleton::ScanImplementation\fP<SU> Scan (SUsu, const size_t &threads = \fC0\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
