.TH "ScanSkeleton" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScanSkeleton \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Scan\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScanImplementation\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename SU2 > \fBScanSkeleton::ScanImplementation\fP
.br
< SU2 > \fB__ScanWithAccess\fP (SU2 su, const size_t &threads)"
.br
.in -1c
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename SU2 > \fBScanSkeleton::ScanImplementation\fP<SU2> __ScanWithAccess (SU2su, const size_t &threads)\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
