.TH "Stage3" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stage3 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Pipeline\&.hpp>\fP
.PP
Inherits \fBPipeStage< string, double >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
