.TH "/afs/inf.ed.ac.uk/user/s18/s1837296/dev/stencil/Distribute/Stencil.hpp" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/afs/inf.ed.ac.uk/user/s18/s1837296/dev/stencil/Distribute/Stencil.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStencilSkeleton\fP"
.br
.ti -1c
.RI "class \fBStencilSkeleton::StencilImplementation< EL >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
