.TH "SummedArea::ThreadArgGetArea" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SummedArea::ThreadArgGetArea \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBsampleIndexStart\fP"
.br
.ti -1c
.RI "size_t \fBsampleIndexEnd\fP"
.br
.ti -1c
.RI "double \fBdx\fP"
.br
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "std::vector< double > * \fBsamples\fP"
.br
.ti -1c
.RI "std::vector< double > * \fBsampleArea\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double SummedArea::ThreadArgGetArea::dx"

.SS "int SummedArea::ThreadArgGetArea::n"

.SS "std::vector<double>* SummedArea::ThreadArgGetArea::sampleArea"

.SS "size_t SummedArea::ThreadArgGetArea::sampleIndexEnd"

.SS "size_t SummedArea::ThreadArgGetArea::sampleIndexStart"

.SS "std::vector<double>* SummedArea::ThreadArgGetArea::samples"


.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
