.TH "SummedArea::ThreadArgGetSummedArea" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SummedArea::ThreadArgGetSummedArea \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBchunkStart\fP"
.br
.ti -1c
.RI "size_t \fBchunkEnd\fP"
.br
.ti -1c
.RI "std::vector< double > * \fBsampleArea\fP"
.br
.ti -1c
.RI "std::vector< double > * \fBsummedArea\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "size_t SummedArea::ThreadArgGetSummedArea::chunkEnd"

.SS "size_t SummedArea::ThreadArgGetSummedArea::chunkStart"

.SS "std::vector<double>* SummedArea::ThreadArgGetSummedArea::sampleArea"

.SS "std::vector<double>* SummedArea::ThreadArgGetSummedArea::summedArea"


.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
