.TH "/afs/inf.ed.ac.uk/user/s18/s1837296/dev/stencil/Distribute/testReduce.cpp" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/afs/inf.ed.ac.uk/user/s18/s1837296/dev/stencil/Distribute/testReduce.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cassert>\fP
.br
\fC#include 'testReduce\&.hpp'\fP
.br
\fC#include 'def_file\&.hpp'\fP
.br
\fC#include 'miscFun\&.hpp'\fP
.br
\fC#include 'Reduce\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBcombine\fP (double a, double b)"
.br
.ti -1c
.RI "int \fBReduceMain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double combine (doublea, doubleb)"

.SS "int ReduceMain (intargc, char **argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
