.TH "/afs/inf.ed.ac.uk/user/s18/s1837296/dev/stencil/Distribute/test.py" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/afs/inf.ed.ac.uk/user/s18/s1837296/dev/stencil/Distribute/test.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBtest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBtest\&.getDefines\fP"
.br
.ti -1c
.RI "def \fBtest\&.execCommand\fP"
.br
.ti -1c
.RI "def \fBtest\&.getCollatzSteps\fP"
.br
.ti -1c
.RI "def \fBtest\&.plotBenchResult\fP"
.br
.ti -1c
.RI "def \fBtest\&.plotSummedAreaTiming\fP"
.br
.ti -1c
.RI "def \fBtest\&.plotKMeansData\fP"
.br
.ti -1c
.RI "def \fBtest\&.plotKMeansTiming\fP"
.br
.ti -1c
.RI "def \fBtest\&.testBench\fP"
.br
.ti -1c
.RI "def \fBtest\&.testProbl\fP"
.br
.ti -1c
.RI "def \fBtest\&.main\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtest\&.stream\fP = False"
.br
.ti -1c
.RI "\fBtest\&.showFig\fP = True"
.br
.ti -1c
.RI "\fBtest\&.log\fP = False"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
