.TH "test" 3 "Mon Mar 18 2019" "DICE-friendlySkeletons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBgetDefines\fP"
.br
.ti -1c
.RI "def \fBexecCommand\fP"
.br
.ti -1c
.RI "def \fBgetCollatzSteps\fP"
.br
.ti -1c
.RI "def \fBplotBenchResult\fP"
.br
.ti -1c
.RI "def \fBplotSummedAreaTiming\fP"
.br
.ti -1c
.RI "def \fBplotKMeansData\fP"
.br
.ti -1c
.RI "def \fBplotKMeansTiming\fP"
.br
.ti -1c
.RI "def \fBtestBench\fP"
.br
.ti -1c
.RI "def \fBtestProbl\fP"
.br
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBstream\fP = False"
.br
.ti -1c
.RI "\fBshowFig\fP = True"
.br
.ti -1c
.RI "\fBlog\fP = False"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def test\&.execCommand (command)"

.SS "def test\&.getCollatzSteps (seed)"

.SS "def test\&.getDefines (options)"

.SS "def test\&.main ()"

.SS "def test\&.plotBenchResult (output, figureName)"

.SS "def test\&.plotKMeansData (output, figureName)"

.SS "def test\&.plotKMeansTiming (output, figureName)"

.SS "def test\&.plotSummedAreaTiming (output, figureName)"

.SS "def test\&.testBench (options)"

.SS "def test\&.testProbl (options)"

.SH "Variable Documentation"
.PP 
.SS "test\&.log = False"

.SS "test\&.showFig = True"

.SS "test\&.stream = False"

.SH "Author"
.PP 
Generated automatically by Doxygen for DICE-friendlySkeletons from the source code\&.
